# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - n2w-converter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e8f2a3986c1445fad7f9a0635ad74c4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_57f72fa154754650b7feea014e682be2 }}

    - name: Pull and Run Docker Compose
      run: |
        echo "version: '3.8'" > docker-compose.yml
        echo "services:" >> docker-compose.yaml
        echo "  api:" >> docker-compose.yaml
        echo "    image: nasminzain/n2w-converter-api:latest" >> docker-compose.yml
        echo "    ports:" >> docker-compose.yaml
        echo "      - '3030:8080'" >> docker-compose.yaml
        echo "  client:" >> docker-compose.yml
        echo "    image: nasminzain/n2w-converter-client:latest" >> docker-compose.yaml
        echo "    ports:" >> docker-compose.yaml
        echo "      - '3000:3000'" >> docker-compose.yaml
        echo "    environment:
        echo "      - REACT_APP_BASE_URL=http://localhost:3030
        docker-compose up -d

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'n2w-converter'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b77292692d0d4078aa3ce969836d32e7 }}
        images: |
          nasminzain/n2w-converter-api:latest
          nasminzain/n2w-converter-client:latest
