# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - n2w-converter-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6ba1f32c5df045458ab55f6fe2e3b480 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_58ef204029234065b08dc922dc4f46cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6ba1f32c5df045458ab55f6fe2e3b480 }}/n2w-converter-client:latest
        file: ./client/Dockerfile
        context: ./client

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'n2w-converter-app'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_65190f04e41f4ba1b3a54948466e740c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6ba1f32c5df045458ab55f6fe2e3b480 }}/n2w-converter-client:latest'